-- MySQL Script generated by MySQL Workbench
-- 10/11/17 12:41:02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema currency
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema currency
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `currency` DEFAULT CHARACTER SET utf8 ;
USE `currency` ;

-- -----------------------------------------------------
-- Table `currency`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `currency`.`users` ;

CREATE TABLE IF NOT EXISTS `currency`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` CHAR(60) NOT NULL,
  `balance` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `currency`.`subscription_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `currency`.`subscription_types` ;

CREATE TABLE IF NOT EXISTS `currency`.`subscription_types` (
  `type` ENUM('week', 'month', 'year') NOT NULL,
  `cost` DECIMAL(7,2) NOT NULL,
  PRIMARY KEY (`type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `currency`.`subscriptions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `currency`.`subscriptions` ;

CREATE TABLE IF NOT EXISTS `currency`.`subscriptions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `type` ENUM('week', 'month', 'year') NOT NULL,
  `subscription_date` DATETIME NOT NULL,
  `end_date` DATETIME NOT NULL,
  `is_active` ENUM('yes', 'no') NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_subscr_type_idx` (`type` ASC),
  INDEX `fk_user_id_idx` (`user_id` ASC),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC),
  CONSTRAINT `fk_subscr_type`
    FOREIGN KEY (`type`)
    REFERENCES `currency`.`subscription_types` (`type`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_subscr_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `currency`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `currency`.`analytics_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `currency`.`analytics_types` ;

CREATE TABLE IF NOT EXISTS `currency`.`analytics_types` (
  `type` ENUM('day', 'week', 'month') NOT NULL,
  `cost` DECIMAL(7,2) NOT NULL,
  PRIMARY KEY (`type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `currency`.`analytics_orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `currency`.`analytics_orders` ;

CREATE TABLE IF NOT EXISTS `currency`.`analytics_orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `type` ENUM('day', 'week', 'month') NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_id_idx` (`user_id` ASC),
  INDEX `fk_a_type_idx` (`type` ASC),
  CONSTRAINT `fk_a_o_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `currency`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_a_type`
    FOREIGN KEY (`type`)
    REFERENCES `currency`.`analytics_types` (`type`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
